#ifndef GUARD_MOD_CATALOG_H
#define GUARD_MOD_CATALOG_H

#include "mod/base.h"

#define MOD_CATALOG_SCHEMA_HASH 0x00000006

#define MOD_CATALOG_ENTRY_FLAG_HOOK_REF (1 << 0)

enum ModCatalogEntryType
{
    MOD_CATALOG_ENTRY_TEXT = 1,
    MOD_CATALOG_ENTRY_WEATHER,
    MOD_CATALOG_ENTRY_ENGINE,
    MOD_CATALOG_ENTRY_NPC,
    MOD_CATALOG_ENTRY_SPRITE_ASSET,
    MOD_CATALOG_ENTRY_BADGE_EFFECT,
    MOD_CATALOG_ENTRY_FISHING_ACTION,
    MOD_CATALOG_ENTRY_ENCOUNTER,
    MOD_CATALOG_ENTRY_SHOP,
    MOD_CATALOG_ENTRY_ITEM,
    MOD_CATALOG_ENTRY_REWARD,
    MOD_CATALOG_ENTRY_POKEMON_DATA,
    MOD_CATALOG_ENTRY_BATTLE_MOVE,
    MOD_CATALOG_ENTRY_TRAINER,
};

struct ModCatalogEntry
{
    u8 type;
    u8 flags;
    u16 reserved;
    u32 key_hash;
    u32 content_hash;
} __attribute__((packed));

#endif // GUARD_MOD_CATALOG_H
