#!/usr/bin/env python3
"""Generate the day/night tint include from JSON."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


MOD_ROOT = Path(__file__).resolve().parents[1]
CONFIG = MOD_ROOT / "tools" / "config" / "tints.json"
OUTPUT = MOD_ROOT / "time" / "generated_tints.inc"


def load_tints(path: Path) -> list[dict[str, int]]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError("tints config must contain an object")
    hours = data.get("hours")
    if not isinstance(hours, list) or len(hours) != 24:
        raise ValueError("hours must contain exactly 24 entries")

    by_hour: dict[int, dict[str, int]] = {}
    for index, raw_hour in enumerate(hours):
        if not isinstance(raw_hour, dict):
            raise ValueError(f"hours[{index}] must be an object")
        hour = require_int(raw_hour.get("hour"), f"hours[{index}].hour", 0, 23)
        if hour in by_hour:
            raise ValueError(f"duplicate hour {hour}")
        by_hour[hour] = {
            "hour": hour,
            "r": require_int(raw_hour.get("r"), f"hours[{index}].r", 0, 512),
            "g": require_int(raw_hour.get("g"), f"hours[{index}].g", 0, 512),
            "b": require_int(raw_hour.get("b"), f"hours[{index}].b", 0, 512),
        }

    missing = [hour for hour in range(24) if hour not in by_hour]
    if missing:
        raise ValueError(f"missing hour {missing[0]}")
    return [by_hour[hour] for hour in range(24)]


def load_map_overrides(path: Path) -> list[dict[str, int | str]]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError("tints config must contain an object")
    raw_overrides = data.get("mapOverrides", [])
    if not isinstance(raw_overrides, list):
        raise ValueError("mapOverrides must be a list")
    overrides: list[dict[str, int | str]] = []
    seen: set[str] = set()
    for index, raw_override in enumerate(raw_overrides):
        if not isinstance(raw_override, dict):
            raise ValueError(f"mapOverrides[{index}] must be an object")
        map_section = raw_override.get("mapSection")
        if not isinstance(map_section, str) or not map_section.startswith("MAPSEC_"):
            raise ValueError(f"mapOverrides[{index}].mapSection must be a MAPSEC_* token")
        if map_section in seen:
            raise ValueError(f"duplicate map override {map_section}")
        seen.add(map_section)
        overrides.append(
            {
                "mapSection": map_section,
                "r": require_int(raw_override.get("r"), f"mapOverrides[{index}].r", 0, 512),
                "g": require_int(raw_override.get("g"), f"mapOverrides[{index}].g", 0, 512),
                "b": require_int(raw_override.get("b"), f"mapOverrides[{index}].b", 0, 512),
            }
        )
    return overrides


def require_int(value: Any, label: str, minimum: int, maximum: int) -> int:
    if isinstance(value, bool) or not isinstance(value, int):
        raise ValueError(f"{label} must be an integer")
    if value < minimum or value > maximum:
        raise ValueError(f"{label} must be in [{minimum}, {maximum}]")
    return value


def render(tints: list[dict[str, int]], map_overrides: list[dict[str, int | str]]) -> str:
    lines = [
        "/* Generated by tools/generate_day_night_tints.py. Do not edit by hand. */",
        "",
        "static const struct DayNightTint sHourlyTints[24] =",
        "{",
    ]
    for tint in tints:
        lines.append(
            "    {{ {r}, {g}, {b} }}, // {hour:02d}".format(
                r=tint["r"],
                g=tint["g"],
                b=tint["b"],
                hour=tint["hour"],
            )
        )
    lines.append("};")
    lines.extend(["", "static const struct DayNightMapTintOverride sMapTintOverrides[] =", "{"])
    if not map_overrides:
        lines.append("    { 0xFFFF, { 256, 256, 256 } },")
    for override in map_overrides:
        lines.append(
            "    {{ {mapSection}, {{ {r}, {g}, {b} }} }},".format(
                mapSection=override["mapSection"],
                r=override["r"],
                g=override["g"],
                b=override["b"],
            )
        )
    lines.append("};")
    return "\n".join(lines) + "\n"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=CONFIG)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--validate-only", action="store_true")
    return parser


def main() -> int:
    args = build_parser().parse_args()
    try:
        content = render(load_tints(args.config), load_map_overrides(args.config))
    except ValueError as exc:
        print(f"day_night_cycle tint generation failed: {exc}", file=sys.stderr)
        return 1

    if args.validate_only:
        print(f"{args.config} is valid")
        return 0

    if args.check:
        existing = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        if existing != content:
            print(f"error: {args.output} is out of date", file=sys.stderr)
            return 1
        print(f"{args.output} is up to date")
        return 0

    args.output.write_text(content, encoding="utf-8")
    print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
