#!/usr/bin/env python3
"""Generate Fishing Memory actions and C cap table from JSON."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


MOD_ROOT = Path(__file__).resolve().parents[1]
CONFIG = MOD_ROOT / "tools" / "config" / "default.json"
ACTIONS = MOD_ROOT / "fishing" / "actions.json"
CAPS_INC = MOD_ROOT / "src" / "generated_cap_stages.inc"
RODS = ("OLD", "GOOD", "SUPER")


def fail(message: str) -> None:
    raise ValueError(message)


def require_int(value: Any, label: str, minimum: int, maximum: int) -> int:
    if isinstance(value, bool) or not isinstance(value, int):
        fail(f"{label} must be an integer")
    if value < minimum or value > maximum:
        fail(f"{label} must be in [{minimum}, {maximum}]")
    return value


def load_config(path: Path) -> dict[str, Any]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        fail("config must contain an object")
    return data


def setting(config: dict[str, Any], rod: str, field: str, minimum: int, maximum: int) -> int:
    rod_settings = config.get("rodSettings", {})
    value = config.get(field)
    if isinstance(rod_settings, dict) and isinstance(rod_settings.get(rod), dict):
        value = rod_settings[rod].get(field, value)
    return require_int(value, f"rodSettings.{rod}.{field}", minimum, maximum)


def render_actions(config: dict[str, Any]) -> str:
    actions: list[dict[str, Any]] = []
    for priority, rod in enumerate(RODS):
        input_frames = setting(config, rod, "inputFrames", 1, 600)
        actions.append(
            {
                "id": f"bite_memory_game_{rod.lower()}",
                "hook": "FishingMemory_Start",
                "hookKey": "memory_sequence",
                "rods": [rod],
                "phases": ["INPUT_WINDOW"],
                "priority": priority,
                "timeoutFrames": input_frames,
                "failureOutcome": config.get("zeroScoreOutcome", "GOT_AWAY"),
                "params": [
                    setting(config, rod, "maxEarnedLevel", 1, 100),
                    setting(config, rod, "showFrames", 1, 600),
                    input_frames,
                    setting(config, rod, "warningFrames", 0, 600),
                ],
            }
        )
    return json.dumps({"actions": actions}, indent=2, ensure_ascii=True) + "\n"


def render_caps(config: dict[str, Any]) -> str:
    stages = config.get("capStages")
    if not isinstance(stages, list) or not stages:
        fail("capStages must be a non-empty list")
    lines = [
        "/* Generated by tools/generate_fishing_memory.py. Do not edit by hand. */",
        "",
        f"#define FISHING_MEMORY_SAFE_MIN_LEVEL {require_int(config.get('safeMinLevel', 1), 'safeMinLevel', 1, 100)}",
        "",
        *render_target_level_difficulty(config),
        "",
        "static const struct FishingMemoryCapStage sFishingMemoryCapStages[] =",
        "{",
    ]
    for index, stage in enumerate(stages):
        if not isinstance(stage, dict):
            fail(f"capStages[{index}] must be an object")
        level = require_int(stage.get("level"), f"capStages[{index}].level", 1, 100)
        flag = stage.get("flag")
        if flag in (None, ""):
            flag_expr = "MOD_FLAG_INVALID"
        elif isinstance(flag, str) and flag.startswith("FLAG_"):
            flag_expr = f"MOD_FLAG_TO_VANILLA({flag})"
        elif isinstance(flag, str):
            flag_expr = flag
        else:
            fail(f"capStages[{index}].flag must be a string")
        level_expr = "MAX_LEVEL" if level == 100 else str(level)
        lines.append(f"    {{ {flag_expr}, {level_expr} }},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def render_target_level_difficulty(config: dict[str, Any]) -> list[str]:
    difficulty = config.get("targetLevelDifficulty", {})
    if not isinstance(difficulty, dict):
        fail("targetLevelDifficulty must be an object")
    enabled = "TRUE" if difficulty.get("enabled", False) is True else "FALSE"
    return [
        f"#define FISHING_MEMORY_TARGET_LEVEL_DIFFICULTY_ENABLED {enabled}",
        f"#define FISHING_MEMORY_TARGET_LEVEL_DIFFICULTY_STEP {require_int(difficulty.get('levelStep', 10), 'targetLevelDifficulty.levelStep', 1, 100)}",
        f"#define FISHING_MEMORY_TARGET_LEVEL_SHOW_FRAME_PENALTY {require_int(difficulty.get('showFramePenalty', 0), 'targetLevelDifficulty.showFramePenalty', 0, 600)}",
        f"#define FISHING_MEMORY_TARGET_LEVEL_INPUT_FRAME_PENALTY {require_int(difficulty.get('inputFramePenalty', 0), 'targetLevelDifficulty.inputFramePenalty', 0, 600)}",
        f"#define FISHING_MEMORY_TARGET_LEVEL_MIN_SHOW_FRAMES {require_int(difficulty.get('minimumShowFrames', 1), 'targetLevelDifficulty.minimumShowFrames', 1, 600)}",
        f"#define FISHING_MEMORY_TARGET_LEVEL_MIN_INPUT_FRAMES {require_int(difficulty.get('minimumInputFrames', 1), 'targetLevelDifficulty.minimumInputFrames', 1, 600)}",
    ]


def write_or_check(path: Path, content: str, check: bool) -> bool:
    if check:
        existing = path.read_text(encoding="utf-8") if path.exists() else ""
        if existing != content:
            print(f"error: {path} is out of date", file=sys.stderr)
            return False
        print(f"{path} is up to date")
        return True
    path.write_text(content, encoding="utf-8")
    print(f"wrote {path}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=CONFIG)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    try:
        config = load_config(args.config)
        ok = write_or_check(ACTIONS, render_actions(config), args.check)
        ok = write_or_check(CAPS_INC, render_caps(config), args.check) and ok
    except ValueError as exc:
        print(f"fishing_memory generation failed: {exc}", file=sys.stderr)
        return 1
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
