#ifndef GUARD_MULTIPLAYER_CONSTANTS_H
#define GUARD_MULTIPLAYER_CONSTANTS_H

#define MAX_NET_PLAYERS 8
#define MAX_NET_REMOTE_PLAYERS (MAX_NET_PLAYERS - 1)
#define MAX_NET_BATTLE_PLAYERS 4
#define MAX_NET_PVE_PLAYERS 2
#define MAX_NET_TRADE_PLAYERS 2
#define MAX_NET_SUBSESSIONS 4

#define NET_PLAYER_NONE 0xFF
#define NET_SUBSESSION_NONE 0

#define NET_PROTOCOL_VERSION 1
#define NET_PROTOCOL_MAGIC 0x504D4D50 // "PMMP"

#define NET_EMULATOR_BRIDGE_MAGIC 0x3844454E // "NED8"
#define NET_EMULATOR_BRIDGE_VERSION 1
#define NET_EMULATOR_SHARED_BASE 0x10000000

#define NET_REMOTE_PLAYER_LOCAL_ID_BASE 248

#define NET_PLAYER_FLAG_BUSY          (1 << 0)
#define NET_PLAYER_FLAG_IN_SUBSESSION (1 << 1)
#define NET_PLAYER_FLAG_HIDDEN        (1 << 2)

#define NET_SUBSESSION_TIMEOUT_FRAMES (60 * 10)

#endif // GUARD_MULTIPLAYER_CONSTANTS_H
