#ifndef GUARD_MULTIPLAYER_CONSTANTS_H
#define GUARD_MULTIPLAYER_CONSTANTS_H

#define MAX_NET_PLAYERS 8
#define MAX_NET_REMOTE_PLAYERS (MAX_NET_PLAYERS - 1)
#define MAX_NET_BATTLE_PLAYERS 4
#define MAX_NET_PVE_PLAYERS 2
#define MAX_NET_TRADE_PLAYERS 2
#define MAX_NET_SUBSESSIONS 4

#define NET_PLAYER_NONE 0xFF
#define NET_SUBSESSION_NONE 0

#define NET_PROTOCOL_VERSION 7
#define NET_PROTOCOL_MAGIC 0x504D4D50 // "PMMP"
#define NET_PROTOCOL_BUILD_ID 0x00010000
#define NET_PROTOCOL_ROM_HASH 0x00000000
#define NET_RULESET_HASH 0x00000003

#define NET_EMULATOR_BRIDGE_MAGIC 0x3844454E // "NED8"
#define NET_EMULATOR_BRIDGE_VERSION 7
#define NET_EMULATOR_SHARED_BASE 0x10000000
#define NET_TRANSPORT_MODE_SERVER_BRIDGE 1

#define NET_SERVER_PROFILE_COUNT 3
#define NET_SERVER_LABEL_LENGTH 12
#define NET_DEFAULT_SERVER_PORT 7777

#define NET_FEATURE_FLAG_MULTIPLAYER        (1 << 0)
#define NET_FEATURE_FLAG_EMULATOR_TRANSPORT (1 << 1)
#define NET_FEATURE_FLAG_ENGINE_GEN1        (1 << 2)
#define NET_FEATURE_FLAG_ENGINE_GEN2        (1 << 3)
#define NET_FEATURE_FLAG_ENGINE_GEN3        (1 << 4)

// Reserved above scripted audience IDs (0-31) and Union Room virtual IDs (200-239).
#define NET_REMOTE_PLAYER_VIRTUAL_ID_BASE 248
#define NET_REMOTE_PLAYER_VIRTUAL_ID_END (NET_REMOTE_PLAYER_VIRTUAL_ID_BASE + MAX_NET_REMOTE_PLAYERS - 1)

#define NET_PLAYER_FLAG_BUSY          (1 << 0)
#define NET_PLAYER_FLAG_IN_SUBSESSION (1 << 1)
#define NET_PLAYER_FLAG_HIDDEN        (1 << 2)
#define NET_PLAYER_FLAG_STALE         (1 << 3)
#define NET_PLAYER_FLAG_RESYNC        (1 << 4)
#define NET_PLAYER_FLAGS_MASK (NET_PLAYER_FLAG_BUSY | NET_PLAYER_FLAG_IN_SUBSESSION | NET_PLAYER_FLAG_HIDDEN | NET_PLAYER_FLAG_STALE | NET_PLAYER_FLAG_RESYNC)

#define NET_HEARTBEAT_INTERVAL_FRAMES 30
#define NET_PLAYER_STALE_FRAMES (60 * 2)
#define NET_PLAYER_DISCONNECT_FRAMES (60 * 10)
#define NET_SUBSESSION_TIMEOUT_FRAMES (60 * 10)
#define NET_SUBSESSION_ACTIVE_TIMEOUT_FRAMES (60 * 30)
#define NET_PLAYER_SNAPSHOT_TTL_FRAMES (60 * 5)
#define NET_PLAYER_SNAPSHOT_FUTURE_SKEW_FRAMES 30
#define NET_PACKET_RATE_LIMIT_PER_TICK 1
#define NET_ANOMALY_THRESHOLD_RESYNC 3
#define NET_ANOMALY_THRESHOLD_KICK 8
#define NET_COMMIT_LOG_SIZE 32
#define NET_RELIABLE_QUEUE_SIZE 16
#define NET_PENDING_TX_COUNT 16
#define NET_TRANSPORT_PACKET_PAYLOAD_SIZE 256
#define NET_PENDING_TX_RETRY_FRAMES 15
#define NET_PENDING_TX_MAX_RETRIES 20
#define NET_CLIENT_HELLO_RETRY_FRAMES 30
#define NET_CLIENT_HELLO_MAX_RETRIES 20
#define NET_PLAYER_COORD_MIN (-512)
#define NET_PLAYER_COORD_MAX 8191
#define NET_PLAYER_INTERACTION_RANGE_TILES 2
#define NET_INTERACTION_BARRIER_TIMEOUT_FRAMES (60 * 5)
#define NET_INTERACTION_RESOURCE_LOCK_MAX 4

#if NET_REMOTE_PLAYER_VIRTUAL_ID_END > 254
#error "Remote player virtual object IDs must not overlap LOCALID_PLAYER/255."
#endif

#endif // GUARD_MULTIPLAYER_CONSTANTS_H
